### PR TITLE
Added Famous Graph Algorithms C++

### PR DESCRIPTION
**Pull request by KartikeySharma**
I have implemented various important algorithms used in competitive coding .
Fixes Issue #35

### CODE REVIEW

**Comment by KartikeySharma** [comment]
Please review @orvil1026 @csendranshi @clare0901

**Review by orvil1026 — APPROVED** [review]

**Comment by KartikeySharma** [comment]
@orvil1026 After this PR is merged, pls assign issue #38  and #37 to me. I have worked on them and have implemented the algorithm and created the app. I am just waiting for those issues to be assigned to be as it is mentioned in the Code of Conduct that I can only work on them after they have been assigned. Thanks :)

**Review by csendranshi — CHANGES_REQUESTED** [review]
Please add the files under SoftwareDev respective language

**Comment by KartikeySharma** [comment]
Updated the location of the files. Pls review @csendranshi

**Comment by orvil1026** [comment]
> @orvil1026 After this PR is merged, pls assign issue #38 and #37 to me. I have worked on them and have implemented the algorithm and created the app. I am just waiting for those issues to be assigned to be as it is mentioned in the Code of Conduct that I can only work on them after they have been assigned. Thanks :)

Issue #37 has been assigned to you.After you make an pr for #37 issue #38 will be assigned to you.

**Review by orvil1026 — APPROVED** [review]

**Review by csendranshi — APPROVED** [review]

**Pull request merged**
