### PR TITLE
Add Hello World Program

### LINKED ISSUE #207: Software Dev: Hello World in Kotlin

### PR DESCRIPTION
**Pull request by KartikeySharma**
Fix #207

### CODE REVIEW

**Comment by KartikeySharma** [comment]
Pls allot issue #207 to me. I forgot about the rule...sorry about that @orvil1026

**Comment by KartikeySharma** [comment]
Ok..no problem

**Comment by clare0901** [comment]
You didn't follow our contribution guidelines hence this PR wont't count as a valid contribution.
You may send this PR again once issue is assigned to you!

**Comment by KartikeySharma** [comment]
Yeah I agree....can you pls allot the issue if possible

**Pull request closed without merging**
