### PR TITLE
Program to use Arduino to cause an LED to fade

### PR DESCRIPTION
**Pull request by KartikeySharma**
My first contribution to OpenOctober

### CODE REVIEW

**Review by orvil1026 — APPROVED** [review]

**Comment by KartikeySharma** [comment]
What does this error mean? @orvil1026

**Comment by orvil1026** [comment]
It is just the greetings bot from github actions .Nothing to worry about.

**Comment by KartikeySharma** [comment]
Ok

**Comment by KartikeySharma** [comment]
So this file cannot be merged in the master repository?

**Comment by orvil1026** [comment]
No,it will be merged soon.

**Comment by KartikeySharma** [comment]
Cool

**Comment by KartikeySharma** [comment]
Closes #43

**Review by csendranshi — APPROVED** [review]

**Pull request merged**
